#!/bin/bash

#PBS -l nodes=1:ppn=1
#PBS -l walltime=00:05:00

#parse config.json for input parameters
out1=$(jq -r .dwi_dir config.json)
#./snr_in_cc.py "$out1"
#SINGULARITYENV_PYTHONNOUSERSITE=true singularity exec -e docker://brainlife/dipy:0.14.1 ./snr_in_cc.py "$out1"
time singularity exec -e docker://brainlife/dipy:0.16.0 ./snr_in_cc.py "$out1"
