#!/bin/bash

#PBS -l nodes=1:ppn=8
#PBS -l walltime=00:40:00

#parse config.json for input parameters
out1=$(jq -r .dwi config.json)
out2=$(jq -r .bvals config.json)
out3=$(jq -r .bvecs config.json)

singularity exec -e docker://brainlife/dipy:0.16.0 ./snr_in_cc.py "$out1" "$out2" "$out3"
#./snr_in_cc.py "$out1" "$out2" "$out3"

singularity exec -e docker://brainlife/freesurfer-stats:1.2 ./convert_snr_json_to_csv.py

mkdir cc_mask && mkdir noise_mask
mv cc.nii.gz cc_mask/mask.nii.gz && mv mask_noise.nii.gz noise_mask/mask.nii.gz
